//! Generation of the binary/document assets referenced by publication links:
//! a minimal but valid EPUB 3 for open-access downloads and an SVG placeholder
//! for cover images.
//!
//! In a real server these would come from storage; here they are synthesized on
//! the fly so every acquisition and image link a feed advertises actually
//! resolves.

use std::io::{Cursor, Write};

use zip::write::SimpleFileOptions;
use zip::{CompressionMethod, ZipWriter};

use crate::catalog::Book;

/// Escape the five XML predefined entities so book metadata can be embedded in
/// XHTML/OPF/SVG documents.
fn xml_escape(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

const CONTAINER_XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"#;

fn content_opf(book: &Book) -> String {
    let title = xml_escape(&book.title);
    let author = xml_escape(&book.author);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="pub-id">urn:opds:book:{id}</dc:identifier>
    <dc:title>{title}</dc:title>
    <dc:creator>{author}</dc:creator>
    <dc:language>{language}</dc:language>
    <meta property="dcterms:modified">{modified}</meta>
  </metadata>
  <manifest>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="ch1" href="chapter1.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine>
    <itemref idref="ch1"/>
  </spine>
</package>
"#,
        id = book.id,
        language = book.language.as_deref().unwrap_or("en"),
        modified = book.modified.as_deref().unwrap_or("1970-01-01T00:00:00Z"),
    )
}

fn nav_xhtml(book: &Book) -> String {
    let title = xml_escape(&book.title);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <head><title>{title}</title></head>
  <body>
    <nav epub:type="toc" id="toc">
      <h1>Contents</h1>
      <ol><li><a href="chapter1.xhtml">{title}</a></li></ol>
    </nav>
  </body>
</html>
"#
    )
}

fn chapter_xhtml(book: &Book) -> String {
    let title = xml_escape(&book.title);
    let author = xml_escape(&book.author);
    let description = xml_escape(book.description.as_deref().unwrap_or_default());
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head><title>{title}</title></head>
  <body>
    <h1>{title}</h1>
    <p><em>by {author}</em></p>
    <p>{description}</p>
    <p>This is a placeholder EPUB generated by opds-axum for demonstration purposes.</p>
  </body>
</html>
"#
    )
}

/// Build a minimal, structurally-valid EPUB 3 file for `book`.
///
/// The archive follows the OCF layout: an uncompressed `mimetype` entry first,
/// then the container descriptor and an OEBPS package with a nav document and a
/// single chapter.
pub fn epub_bytes(book: &Book) -> Vec<u8> {
    let mut cursor = Cursor::new(Vec::new());
    {
        let mut zip = ZipWriter::new(&mut cursor);

        // The `mimetype` entry must come first and be stored uncompressed.
        let stored = SimpleFileOptions::default().compression_method(CompressionMethod::Stored);
        zip.start_file("mimetype", stored)
            .expect("start mimetype entry");
        zip.write_all(b"application/epub+zip")
            .expect("write mimetype");

        let deflated =
            SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
        for (name, contents) in [
            ("META-INF/container.xml", CONTAINER_XML.to_string()),
            ("OEBPS/content.opf", content_opf(book)),
            ("OEBPS/nav.xhtml", nav_xhtml(book)),
            ("OEBPS/chapter1.xhtml", chapter_xhtml(book)),
        ] {
            zip.start_file(name, deflated).expect("start entry");
            zip.write_all(contents.as_bytes()).expect("write entry");
        }

        zip.finish().expect("finish zip");
    }
    cursor.into_inner()
}

/// Render an SVG placeholder cover for `book` at the given pixel dimensions,
/// showing the title and author on a solid background.
pub fn cover_svg(book: &Book, width: u32, height: u32) -> String {
    let title = xml_escape(&book.title);
    let author = xml_escape(&book.author);
    // Deterministically pick a background hue from the id so covers differ.
    let hue = book.id.bytes().fold(0u32, |acc, b| acc + b as u32) % 360;
    format!(
        r##"<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <rect width="100%" height="100%" fill="hsl({hue}, 45%, 30%)"/>
  <text x="50%" y="42%" fill="#ffffff" font-family="Georgia, serif" font-size="{title_size}"
        font-weight="bold" text-anchor="middle">{title}</text>
  <text x="50%" y="54%" fill="#dddddd" font-family="Georgia, serif" font-size="{author_size}"
        text-anchor="middle">{author}</text>
</svg>
"##,
        title_size = height / 18,
        author_size = height / 26,
    )
}
